apply plugin: 'com.android.library'
apply plugin: 'maven-publish' // for Jitpack

group='com.github.maxxx.uCrop' // for Jitpack

android {
    compileSdkVersion 35
    namespace "com.yalantis.ucrop"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 35
        consumerProguardFiles = ['proguard-rules.pro']
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig true
    }

    resourcePrefix 'ucrop_'

    sourceSets.main {
        jni.srcDirs = []
    }
    lint {
        abortOnError false
    }

}

dependencies {
    implementation "androidx.appcompat:appcompat:${androidx_appcompat_version}"
    implementation "androidx.exifinterface:exifinterface:${androidx_exifinterface_version}"
    implementation "androidx.transition:transition:${androidx_transition_version}"
    implementation "com.squareup.okhttp3:okhttp:3.12.1"
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

// for Jitpack
publishing {
    publications {
        // Creates a Maven publication called "release".
        release(MavenPublication) {
            groupId = 'com.github.maxxx.uCrop'
            artifactId = 'lib'

            afterEvaluate {
                from components.findByName('release')
            }
        }
    }
}
